# Generated by Django 6.0.3 on 2026-03-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='university',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='year_of_study',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
