# Generated by Django 6.0.3 on 2026-03-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_university_customuser_year_of_study"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="university",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="year_of_study",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="account_status",
            field=models.CharField(
                choices=[
                    ("registered", "Registered"),
                    ("active", "Active"),
                    ("suspended", "Suspended"),
                    ("deactivated", "Deactivated"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="district",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="job_title",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="organisation_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="profile_photo",
            field=models.ImageField(blank=True, upload_to="profile_photos/"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="programme",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="student_number",
            field=models.CharField(blank=True, default="", max_length=50, unique=True),
        ),
    ]
