# Generated by Django 6.0.3 on 2026-04-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_customuser_university_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="univsersity",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="customuser",
            name="year_of_study",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
