# Generated by Django 6.0.3 on 2026-04-06 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_customuser_univsersity_customuser_year_of_study"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="univsersity",
            new_name="university",
        ),
    ]
