# Generated by Django 6.0.3 on 2026-03-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeeklyLogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_number", models.PositiveSmallIntegerField()),
                ("week_start_date", models.DateField()),
                ("week_end_date", models.DateField()),
                (
                    "activities_performed",
                    models.TextField(help_text="Tasks and activities done this week"),
                ),
                (
                    "skills_gained",
                    models.TextField(help_text="Skills or knowledge acquired"),
                ),
                (
                    "challenges_faced",
                    models.TextField(
                        help_text="Difficulties encountered and how resolved"
                    ),
                ),
                (
                    "student_remarks",
                    models.TextField(blank=True, help_text="Any additional remarks"),
                ),
                ("status", models.CharField(max_length=20)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
