# Generated by Django 6.0.3 on 2026-03-24 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0001_initial"),
        ("placements", "0004_internshipplacement_acceptance_letter_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="weeklylogs",
            options={
                "ordering": ["placement", "week_number"],
                "verbose_name": "Weekly Log",
                "verbose_name_plural": "Weekly Logs",
            },
        ),
        migrations.AddField(
            model_name="weeklylogs",
            name="placement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weekly_logs",
                to="placements.internshipplacement",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="weeklylogs",
            unique_together={("placement", "week_number")},
        ),
        migrations.AddField(
            model_name="weeklylogs",
            name="academic_assessed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weeklylogs",
            name="academic_assessed_by",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "academic_supervisor"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assessed_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="weeklylogs",
            name="academic_comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weeklylogs",
            name="academic_grade",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="weeklylogs",
            name="workplace_comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weeklylogs",
            name="workplace_endorsed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weeklylogs",
            name="workplace_endorsed_by",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "workplace_supervisor"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="endorsed_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="weeklylogs",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("under_review", "Under Review"),
                    ("endorsed", "Endorsed"),
                    ("resubmit", "Resubnit"),
                    ("assessed", "Assessed"),
                    ("closed", "Closed"),
                ],
                max_length=20,
            ),
        ),
        migrations.RemoveField(
            model_name="weeklylogs",
            name="student",
        ),
    ]
