# Generated by Django 6.0.3 on 2026-04-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0002_alter_weeklylogs_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="weeklylogs",
            old_name="academic_comment",
            new_name="academic_remarks",
        ),
        migrations.RenameField(
            model_name="weeklylogs",
            old_name="workplace_comment",
            new_name="resubmit_reason",
        ),
        migrations.AddField(
            model_name="weeklylogs",
            name="workplace_remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="weeklylogs",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("under_review", "Under Review"),
                    ("endorsed", "Endorsed"),
                    ("resubmit", "Resubmit"),
                    ("assessed", "Assessed"),
                    ("closed", "Closed"),
                ],
                max_length=20,
            ),
        ),
    ]
