# Generated by Django 6.0.3 on 2026-03-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=255)),
                ('organisation_type', models.CharField(max_length=20)),
                ('organisation_district', models.CharField(max_length=100)),
                ('organisation_address', models.TextField(blank=True)),
                ('department', models.CharField(max_length=200)),
                ('wp_supervisor_name', models.CharField(max_length=200)),
                ('wp_supervisor_email', models.EmailField(max_length=254)),
                ('wp_supervisor_phone', models.CharField(max_length=20)),
                ('wp_supervisor_title', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('withdrawal_reason', models.TextField(blank=True, null=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
