# Generated by Django 6.0.3 on 2026-03-18 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InternshipPlacement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organisation_name", models.CharField(max_length=255)),
                ("organisation_type", models.CharField(max_length=20)),
                ("organisation_district", models.CharField(max_length=100)),
                ("organisation_address", models.TextField(blank=True)),
                ("department", models.CharField(max_length=200)),
                ("wp_supervisor_name", models.CharField(max_length=200)),
                ("wp_supervisor_email", models.EmailField(max_length=254)),
                ("wp_supervisor_phone", models.CharField(max_length=20)),
                ("wp_supervisor_title", models.CharField(blank=True, max_length=200)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("status", models.CharField(max_length=20)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("withdrawal_reason", models.TextField(blank=True, null=True)),
                ("approval_date", models.DateTimeField(blank=True, null=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_supervisor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="internship_placement_academic",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "approval_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="internship_placement_admin",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workplace_supervisor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="internship_placement_workplace",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
