# Generated by Django 6.0.3 on 2026-03-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("placements", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="internshipplacement",
            name="academic_supervisor_name",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
