# Generated by Django 6.0.3 on 2026-03-24 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("placements", "0002_internshipplacement_academic_supervisor_name"),
        ("placements", "0002_internshipplacement_student"),
    ]

    operations = []
