# Generated by Django 6.0.3 on 2026-03-24 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("placements", "0003_merge_20260324_2109"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="internshipplacement",
            name="acceptance_letter",
            field=models.FileField(
                blank=True, null=True, upload_to="acceptance_letters/"
            ),
        ),
        migrations.AddField(
            model_name="internshipplacement",
            name="final_report",
            field=models.FileField(blank=True, null=True, upload_to="final_reports/"),
        ),
        migrations.AddField(
            model_name="internshipplacement",
            name="final_report_abstract",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="internshipplacement",
            name="intake_cohort",
            field=models.CharField(
                blank=True,
                choices=[("january", "January"), ("april", "April"), ("june", "June")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="internshipplacement",
            name="placement_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="internshipplacement",
            name="remuneration_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("paid", "Paid"),
                    ("unpaid", "Unpaid"),
                    ("stipend", "Stipend"),
                ],
                default="unpaid",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="internshipplacement",
            name="report_declaration",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="internshipplacement",
            name="request_letter",
            field=models.FileField(blank=True, null=True, upload_to="request_letters/"),
        ),
        migrations.AlterField(
            model_name="internshipplacement",
            name="academic_supervisor",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "academic_supervisor"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="academic_placements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="internshipplacement",
            name="academic_supervisor_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="internshipplacement",
            name="approval_by",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "internship_administrator"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_placements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="internshipplacement",
            name="organisation_type",
            field=models.CharField(
                choices=[
                    ("private", "Private Company"),
                    ("government", "Government Agency"),
                    ("international", "International Organization"),
                    ("parastatal", "Parastatal"),
                    ("ngo", "Non-Governmental Organization"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="internshipplacement",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending Approval"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("withdrawn", "Withdrawn"),
                    ("active", "Active"),
                    ("completed", "Completed"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="internshipplacement",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"role": "student"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="placements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="internshipplacement",
            name="workplace_supervisor",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "workplace_supervisor"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workplace_placements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
